# This workflow will do a clean install of node dependencies, build the source
# code and run tests in block on the latest version of node.

name: Tests

on:
  push:
    branches: [ zorkwow ]
  pull_request:
    branches: [ develop ]

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Compile SRE with locales
    steps:
      - uses: actions/checkout@v2
      - name: Setup Speech Rule Engine
        run: npm ci; npm run build --if-present; npm run pretest
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: sre-library
          path: |
                lib
                js
                package.json
          
  test:

    strategy:
      matrix:
        block: [ko/mathspeak]
    needs: setup
    runs-on: ubuntu-latest
    name: SRE jests tests for ${{ matrix.block }}
    steps:
      - uses: actions/checkout@v2
      - name: Downloading the build
        uses: actions/download-artifact@v2
        with:
          name: sre-library
      - name: Set up tests
        run: |
          sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
          git submodule update --init --recursive
          npm install
          cd sre-tests; ln -s .. speech-rule-engine; npm install; sudo chmod -R 777 .; npm ci
      - name: Run tests for ${{ matrix.block }}
        run: npm run actionTest js/json/${{ matrix.block }}
